[package]
name = "slimcode"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[[bin]]
name = "slimcode"
path = "src/main.rs"

[dependencies]
slimcode-ai.workspace = true
slimcode-core.workspace = true
slimcode-commands.workspace = true
slimcode-app.workspace = true
slimcode-tui.workspace = true
